<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \HappyMachines\CustomForms\ViewModel\Form\Field|\HappyMachines\CustomForms\Model\Form\Field $fieldViewModel */

$fieldViewModel = $block->getViewModel();
?>
<div class="field <?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getClassName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getRequiredFieldClass()) ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>">
        <span><?= __($block->escapeHtml($fieldViewModel->getLabel())) ?></span>
    </label>
    <div class="control">
        <input type="tel" name="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>"
               title="<?= __($block->escapeHtml($fieldViewModel->getLabel())) ?>"
               id="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>"
               class="input-text <?= $escaper->escapeHtmlAttr($fieldViewModel->getInputClassName()) ?>"
               value="<?= $fieldViewModel->getValue() ?>" <?= $fieldViewModel->getFieldAttributes() ?>>
    </div>
</div>

