<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \HappyMachines\CustomForms\ViewModel\Form\Field|\HappyMachines\CustomForms\Model\Form\Field $fieldViewModel */

$fieldViewModel = $block->getViewModel();
?>
<div class="field <?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getClassName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getRequiredFieldClass()) ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>">
        <span><?= __($block->escapeHtml($fieldViewModel->getLabel())) ?></span>
    </label>
    <div class="control">
        <div class="radio-group">
            <?php /** @var  $option \HappyMachines\CustomForms\Model\Form\Field\Option */ foreach ($fieldViewModel->getValues() as $index => $option): ?>
                <div>
                    <input type="radio" name="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>"
                           title="<?= __($block->escapeHtml($option->getLabel())) ?>"
                           id="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>-<?= $index ?>"
                           class="input-text <?= $escaper->escapeHtmlAttr($fieldViewModel->getInputClassName()) ?>"
                           value="<?= $option->getValue() ?>" <?= $fieldViewModel->getFieldAttributes() ?>
                        <?= $option->isSelected() ? 'checked' : '' ?>>
                    <label for="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>-<?= $index ?>"><?= __($option->getLabel()) ?></label>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

