<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \HappyMachines\CustomForms\ViewModel\Form\Field|\HappyMachines\CustomForms\Model\Form\Field $fieldViewModel */

$fieldViewModel = $block->getViewModel();
?>
<div class="field <?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getClassName()) ?> <?= $escaper->escapeHtmlAttr($fieldViewModel->getRequiredFieldClass()) ?>">
    <label class="label" for="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>">
        <span><?= __($block->escapeHtml($fieldViewModel->getLabel())) ?></span>
    </label>
    <div class="control">
        <select name="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>"
                title="<?= __($block->escapeHtml($fieldViewModel->getLabel())) ?>"
                id="<?= $escaper->escapeHtmlAttr($fieldViewModel->getName()) ?>"
                class="input-text <?= $escaper->escapeHtmlAttr($fieldViewModel->getInputClassName()) ?>"
                <?= $fieldViewModel->getFieldAttributes() ?>>
            <?php /** @var  $option \HappyMachines\CustomForms\Model\Form\Field\Option */ foreach ($fieldViewModel->getValues() as $option): ?>
                <option value="<?= $option->getValue() ?>" label="<?= __($option->getLabel()) ?>" <?= $option->isSelected() ? 'selected' : '' ?>><?= __($option->getLabel()) ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</div>

